//! Differential test for the reconcile matcher, against the live TypeScript.
//!
//! Scenario-driven: each case is one shape the matcher must classify, drawn
//! from the situations its own comments cite as having caused real false
//! positives. Random statements essentially never produce a grouped entry, a
//! sign flip, or a trade near-miss.
//!
//! Compares the full finding list — kind, which rows were paired, and the
//! delta — plus the remainder, because the remainder is what the user is
//! actually shown and a compensating pair of errors would hide in a summary.

use avoir_core::matcher::*;
use avoir_core::money::Cents;
use avoir_core::reconcile::Direction;
use chrono::NaiveDate;
use serde_json::Value;

fn date(s: &str) -> NaiveDate {
    NaiveDate::parse_from_str(s, "%Y-%m-%d").unwrap()
}
fn cents(v: &Value) -> Cents {
    Cents((v.as_f64().unwrap() * 100.0).round() as i64)
}
fn dir(v: &Value) -> Direction {
    match v.as_str().unwrap() {
        "charge" => Direction::Charge,
        "credit" => Direction::Credit,
        o => panic!("unknown direction: {o}"),
    }
}

/// The names come from `FindingKind::as_str`, which the API also uses.
///
/// Sharing is safe precisely here: the expectations below are read from
/// fixtures generated by the TypeScript matcher, so a wrong name in `as_str`
/// disagrees with the fixture and fails. The independence this test needs is
/// from the *implementation*, not from the enum's spelling.
fn kind_name(k: FindingKind) -> &'static str {
    k.as_str()
}

#[test]
fn matcher_matches_typescript_on_every_scenario() {
    let doc: Value = serde_json::from_str(include_str!("fixtures/matcher_vectors.json")).unwrap();
    let cases = doc["cases"].as_array().unwrap();
    assert!(cases.len() >= 19);

    let mut problems = Vec::new();
    let mut findings_compared = 0usize;

    for c in cases {
        let name = c["name"].as_str().unwrap();
        let iv = &c["in"];

        let statement: Vec<StatementLine> = iv["statement"]
            .as_array()
            .unwrap()
            .iter()
            .map(|r| StatementLine {
                id: r["id"].as_str().map(String::from),
                date: date(r["date"].as_str().unwrap()),
                description: r["description"].as_str().unwrap().to_string(),
                amount: cents(&r["amount"]),
                direction: dir(&r["direction"]),
            })
            .collect();

        let app: Vec<AppTx> = iv["app"]
            .as_array()
            .unwrap()
            .iter()
            .map(|r| AppTx {
                id: r["id"].as_str().unwrap().to_string(),
                date: date(r["date"].as_str().unwrap()),
                name: r["name"].as_str().unwrap().to_string(),
                amount: cents(&r["amount"]),
                direction: dir(&r["direction"]),
                is_trade: r["isTrade"].as_bool().unwrap_or(false),
            })
            .collect();

        let mut opts = ReconcileOptions::default();
        if let Some(t) = iv["options"]["sumNameThreshold"].as_f64() {
            opts.sum_name_threshold = t;
        }

        let got = reconcile(
            &statement,
            &app,
            date(iv["endDate"].as_str().unwrap()),
            &opts,
        );
        let want = c["out"]["findings"].as_array().unwrap();

        if got.findings.len() != want.len() {
            problems.push(format!(
                "[{name}] finding count: rust {}, ts {} (rust kinds: {:?})",
                got.findings.len(),
                want.len(),
                got.findings
                    .iter()
                    .map(|f| kind_name(f.kind))
                    .collect::<Vec<_>>()
            ));
            continue;
        }

        for (g, w) in got.findings.iter().zip(want.iter()) {
            findings_compared += 1;
            if kind_name(g.kind) != w["kind"].as_str().unwrap() {
                problems.push(format!(
                    "[{name}] kind: rust {}, ts {}",
                    kind_name(g.kind),
                    w["kind"]
                ));
            }
            let got_sid = g.statement.as_ref().and_then(|s| s.id.clone());
            let want_sid = w["statementId"].as_str().map(String::from);
            if got_sid != want_sid {
                problems.push(format!(
                    "[{name}] statement id: rust {got_sid:?}, ts {want_sid:?}"
                ));
            }
            let got_aid = g.app.as_ref().map(|a| a.id.clone());
            let want_aid = w["appId"].as_str().map(String::from);
            if got_aid != want_aid {
                problems.push(format!(
                    "[{name}] app id: rust {got_aid:?}, ts {want_aid:?}"
                ));
            }
            let got_aids: Vec<String> = g.apps.iter().map(|a| a.id.clone()).collect();
            let want_aids: Vec<String> = w["appIds"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_str().unwrap().to_string())
                .collect();
            if got_aids != want_aids {
                problems.push(format!(
                    "[{name}] grouped app ids: rust {got_aids:?}, ts {want_aids:?}"
                ));
            }
            let got_sids: Vec<String> = g.statements.iter().filter_map(|s| s.id.clone()).collect();
            let want_sids: Vec<String> = w["statementIds"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_str().unwrap().to_string())
                .collect();
            if got_sids != want_sids {
                problems.push(format!(
                    "[{name}] grouped statement ids: rust {got_sids:?}, ts {want_sids:?}"
                ));
            }
            if g.delta != cents(&w["delta"]) {
                problems.push(format!(
                    "[{name}] {} delta: rust {}, ts {}",
                    kind_name(g.kind),
                    g.delta,
                    w["delta"]
                ));
            }
        }

        // The remainder is what the user is shown, so it is checked separately
        // rather than trusted to follow from the findings.
        let want_rem = cents(&c["out"]["remainder"]);
        if got.remainder != want_rem {
            problems.push(format!(
                "[{name}] remainder: rust {}, ts {want_rem}",
                got.remainder
            ));
        }
    }

    println!("  findings compared: {findings_compared}");
    assert!(
        problems.is_empty(),
        "{} divergences:\n{}",
        problems.len(),
        problems
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}
