/**
 * Schedule Generator — creates persisted ScheduledTransaction rows
 * from recurring Expense and Income definitions for a given date range.
 *
 * Replaces the ephemeral anticipation engine with database-backed rows.
 * Uses occurrences() from recurring.ts and applyWeekendShift() for
 * weekend-aware due date calculation.
 */
import { prisma } from '@budget-tracker/db';
import { occurrences, applyWeekendShift } from './recurring.js';
import { localDate, today as todayFn } from './dates.js';
import { isPaused } from './pause.js';
import {
  type UtilityReadingInfo,
  resolveUtilityDueDate,
  resolveExpectedAmount,
} from './schedule-amount-resolver.js';

/**
 * Mark the schedule as dirty — call this when expenses, income, pay schedules,
 * or utility readings change. Currently a no-op since we always regenerate on GET,
 * but retained as the public API for callers that signal mutations.
 */
export function markScheduleDirty(): void {
  // No-op — generation always runs (idempotent via skipDuplicates).
  // Retained for API compatibility with callers in invalidateSchedule, expenses, income routes.
}

interface GenerateOptions {
  periodStart: Date;
  periodEnd: Date;
  /** When set, only generate for this specific source */
  sourceType?: 'EXPENSE' | 'INCOME';
  sourceId?: string;
}

/**
 * Generate ScheduledTransaction rows for the given period.
 *
 * Queries active (non-paused, non-ONE_TIME) Expense and Income records,
 * iterates occurrences() for each source, and reconciles the persisted PENDING
 * rows against the computed occurrences:
 *   - new occurrences are inserted (rows that already exist keep their id),
 *   - the expectedAmount of surviving PENDING rows is refreshed,
 *   - PENDING rows that no longer match a computed occurrence are pruned.
 *
 * Crucially, rows are NOT blindly deleted and recreated, so an occurrence's id
 * is stable across regenerations. A scheduled-transaction id handed to the
 * client therefore stays valid, and mark-as-paid/snooze/skip won't 404 on a
 * stale id after the schedule is regenerated by another request.
 *
 * PAID/PARTIAL/SKIPPED/SNOOZED rows are always preserved as-is.
 *
 * Returns the count of newly created rows.
 */
export async function generateSchedule(options: GenerateOptions): Promise<number> {
  const { periodStart, periodEnd, sourceType, sourceId } = options;

  const now = todayFn();

  // Fetch utility services with expense links and their readings for amount resolution
  const utilityServices = await prisma.utilityService.findMany({
    where: { expenseId: { not: null } },
    select: { id: true, expenseId: true },
  });
  const serviceExpenseMap = new Map(utilityServices.map((s) => [s.id, s.expenseId!]));

  const utilityReadings =
    serviceExpenseMap.size > 0
      ? await prisma.utilityReading.findMany({
          where: { serviceId: { in: [...serviceExpenseMap.keys()] } },
          select: {
            serviceId: true,
            cost: true,
            convenienceFee: true,
            convenienceFeeType: true,
            otherFees: true,
            dueDate: true,
            billDate: true,
          },
        })
      : [];

  const utilReadings: UtilityReadingInfo[] = utilityReadings.map((r) => ({
    expenseId: serviceExpenseMap.get(r.serviceId)!,
    cost: Number(r.cost),
    convenienceFee: r.convenienceFee != null ? Number(r.convenienceFee) : null,
    convenienceFeeType: r.convenienceFeeType,
    otherFees: r.otherFees != null ? Number(r.otherFees) : null,
    dueDate: r.dueDate,
    billDate: r.billDate,
  }));

  const rows: Array<{
    sourceType: 'EXPENSE' | 'INCOME';
    sourceId: string;
    dueDate: Date;
    expectedAmount: number;
    status: 'PENDING';
    expenseId: string | null;
    incomeId: string | null;
  }> = [];

  // Fetch existing non-PENDING rows (PAID, PARTIAL, etc.) for the period so we
  // can skip months that already have a fulfilled row. This prevents ghost PENDING
  // rows when the due date shifts (e.g., utility reading dueDate differs from
  // the Expense's dueDay) and the old date already has a PAID row.
  const existingFulfilled = await prisma.scheduledTransaction.findMany({
    where: {
      dueDate: { gte: periodStart, lte: periodEnd },
      status: { in: ['PAID', 'PARTIAL'] },
    },
    select: { sourceType: true, sourceId: true, dueDate: true },
  });
  // Build a set of "sourceType:sourceId:YYYY-MM" keys for fulfilled months
  const fulfilledMonths = new Set(
    existingFulfilled.map((r) => {
      const d = localDate(r.dueDate);
      return `${r.sourceType}:${r.sourceId}:${d.year}-${d.month}`;
    }),
  );
  // Build a set of exact-date keys for BIWEEKLY/WEEKLY dedup
  const fulfilledDates = new Set(
    existingFulfilled.map((r) => {
      const d = localDate(r.dueDate);
      return `${r.sourceType}:${r.sourceId}:${d.year}-${d.month}-${d.day}`;
    }),
  );

  // --- Expenses ---
  if (!sourceType || sourceType === 'EXPENSE') {
    const expenseWhere: Record<string, unknown> = {
      frequency: { not: 'ONE_TIME' },
      archivedAt: null,
    };
    if (sourceType === 'EXPENSE' && sourceId) {
      expenseWhere.id = sourceId;
    }

    const expenses = await prisma.expense.findMany({ where: expenseWhere });

    for (const exp of expenses) {
      if (isPaused(exp.pausedUntil, now)) continue;

      const baseAmount = Number(exp.amount);
      const schedule = exp.amountSchedule as Record<string, number> | null;

      for (const rawDate of occurrences(
        exp.frequency,
        exp.dueDay,
        exp.dueWeekday,
        exp.dueOrdinal,
        exp.startDate,
        exp.endDate,
        periodStart,
        periodEnd,
      )) {
        let dueDate = applyWeekendShift(rawDate, exp.skipWeekend);

        // If a utility reading has a specific dueDate for this month, use it
        // instead of the generic Expense dueDay. This ensures the dashboard
        // shows the actual bill due date (e.g., May 7) not the Expense default.
        const utilityDueDate = resolveUtilityDueDate(dueDate, utilReadings, exp.id);
        if (utilityDueDate) {
          dueDate = utilityDueDate;
        }

        if (dueDate < periodStart || dueDate > periodEnd) continue;

        // Skip if this source already has a PAID/PARTIAL row.
        // For MONTHLY and longer frequencies, use month-level dedup (handles due date
        // shifts from utility readings). For BIWEEKLY/WEEKLY, use exact date.
        const dueParts = localDate(dueDate);
        if (exp.frequency === 'BIWEEKLY' || exp.frequency === 'WEEKLY') {
          const dateKey = `EXPENSE:${exp.id}:${dueParts.year}-${dueParts.month}-${dueParts.day}`;
          if (fulfilledDates.has(dateKey)) continue;
        } else {
          const monthKey = `EXPENSE:${exp.id}:${dueParts.year}-${dueParts.month}`;
          if (fulfilledMonths.has(monthKey)) continue;
        }

        const expectedAmount = resolveExpectedAmount(
          baseAmount,
          schedule,
          dueDate,
          exp.frequency,
          exp.startDate,
          utilReadings,
          exp.id,
        );

        // Skip $0 amounts — nothing is due this period
        if (expectedAmount === 0) continue;

        rows.push({
          sourceType: 'EXPENSE',
          sourceId: exp.id,
          dueDate,
          expectedAmount,
          status: 'PENDING',
          expenseId: exp.id,
          incomeId: null,
        });
      }
    }
  }

  // --- Incomes ---
  if (!sourceType || sourceType === 'INCOME') {
    const incomeWhere: Record<string, unknown> = {
      frequency: { not: 'ONE_TIME' },
      archivedAt: null,
    };
    if (sourceType === 'INCOME' && sourceId) {
      incomeWhere.id = sourceId;
    }

    const incomes = await prisma.income.findMany({ where: incomeWhere });

    for (const inc of incomes) {
      if (isPaused(inc.pausedUntil, now)) continue;

      const baseAmount = Number(inc.amount);
      const schedule = inc.amountSchedule as Record<string, number> | null;

      for (const rawDate of occurrences(
        inc.frequency,
        null,
        null,
        null,
        inc.startDate,
        inc.endDate,
        periodStart,
        periodEnd,
      )) {
        if (rawDate < periodStart || rawDate > periodEnd) continue;

        // Skip if this source already has a PAID/PARTIAL row for this exact date.
        // For MONTHLY frequencies, we also skip the entire month (prevents ghost rows
        // when utility due dates shift). For BIWEEKLY/WEEKLY, we must allow multiple
        // occurrences in the same month.
        const incParts = localDate(rawDate);
        if (
          inc.frequency === 'MONTHLY' ||
          inc.frequency === 'QUARTERLY' ||
          inc.frequency === 'BIANNUAL' ||
          inc.frequency === 'ANNUAL' ||
          inc.frequency === 'SEMI_MONTHLY'
        ) {
          const incMonthKey = `INCOME:${inc.id}:${incParts.year}-${incParts.month}`;
          if (fulfilledMonths.has(incMonthKey)) continue;
        } else {
          // BIWEEKLY / WEEKLY: check exact date only
          const incDateKey = `INCOME:${inc.id}:${incParts.year}-${incParts.month}-${incParts.day}`;
          if (fulfilledDates.has(incDateKey)) continue;
        }

        const expectedAmount = resolveExpectedAmount(
          baseAmount,
          schedule,
          rawDate,
          inc.frequency,
          inc.startDate,
        );

        // Skip $0 amounts — nothing is due this period
        if (expectedAmount === 0) continue;

        rows.push({
          sourceType: 'INCOME',
          sourceId: inc.id,
          dueDate: rawDate,
          expectedAmount,
          status: 'PENDING',
          expenseId: null,
          incomeId: inc.id,
        });
      }
    }
  }

  // Insert only genuinely new occurrences. skipDuplicates leverages
  // @@unique([sourceType, sourceId, dueDate]) so any row that already exists for
  // an occurrence is left untouched — its id, status, and link are preserved.
  const result =
    rows.length > 0
      ? await prisma.scheduledTransaction.createMany({
          data: rows.map((r) => ({
            sourceType: r.sourceType,
            sourceId: r.sourceId,
            dueDate: r.dueDate,
            expectedAmount: r.expectedAmount,
            status: r.status,
            expenseId: r.expenseId,
            incomeId: r.incomeId,
          })),
          skipDuplicates: true,
        })
      : { count: 0 };

  // Prune PENDING rows in scope that no longer correspond to a computed
  // occurrence (source removed/paused, due date shifted, amount dropped to $0).
  // Only PENDING rows are pruned — PAID/PARTIAL/SKIPPED/SNOOZED are preserved.
  const targetKeys = new Set(
    rows.map((r) => `${r.sourceType}:${r.sourceId}:${r.dueDate.getTime()}`),
  );
  const pruneWhere: Record<string, unknown> = {
    status: 'PENDING',
    dueDate: { gte: periodStart, lte: periodEnd },
  };
  if (sourceType) pruneWhere.sourceType = sourceType;
  if (sourceId) pruneWhere.sourceId = sourceId;
  const existingPending = await prisma.scheduledTransaction.findMany({
    where: pruneWhere,
    select: { id: true, sourceType: true, sourceId: true, dueDate: true },
  });
  const staleIds = existingPending
    .filter((r) => !targetKeys.has(`${r.sourceType}:${r.sourceId}:${r.dueDate.getTime()}`))
    .map((r) => r.id);
  if (staleIds.length > 0) {
    await prisma.scheduledTransaction.deleteMany({ where: { id: { in: staleIds } } });
  }

  // Reconcile surviving rows: keep expectedAmount current (e.g. a utility reading
  // changed) without churning the id, and backward-match any unlinked transaction
  // that was entered before the schedule row existed (±5 days).
  const MATCH_WINDOW_MS = 5 * 86_400_000;
  for (const row of rows) {
    const scheduled = await prisma.scheduledTransaction.findUnique({
      where: {
        sourceType_sourceId_dueDate: {
          sourceType: row.sourceType,
          sourceId: row.sourceId,
          dueDate: row.dueDate,
        },
      },
    });
    if (!scheduled) continue;

    // Refresh the expected amount in place (preserves the row id).
    if (scheduled.status === 'PENDING' && Number(scheduled.expectedAmount) !== row.expectedAmount) {
      await prisma.scheduledTransaction.update({
        where: { id: scheduled.id },
        data: { expectedAmount: row.expectedAmount },
      });
    }

    // Only backward-match PENDING rows with no existing link.
    if (scheduled.status !== 'PENDING' || scheduled.transactionId) continue;

    const windowStart = new Date(row.dueDate.getTime() - MATCH_WINDOW_MS);
    const windowEnd = new Date(row.dueDate.getTime() + MATCH_WINDOW_MS);

    const txWhere =
      row.sourceType === 'EXPENSE' ? { expenseId: row.sourceId } : { incomeId: row.sourceId };

    // Find unlinked transactions for this source within the window
    const candidates = await prisma.transaction.findMany({
      where: {
        ...txWhere,
        date: { gte: windowStart, lte: windowEnd },
      },
    });

    // Filter to those not already linked to any scheduled row
    const unlinked = (
      await Promise.all(
        candidates.map(async (tx) => {
          const existing = await prisma.scheduledTransaction.findUnique({
            where: { transactionId: tx.id },
          });
          return existing ? null : tx;
        }),
      )
    ).filter(Boolean) as typeof candidates;

    if (unlinked.length === 0) continue;

    // Pick closest to dueDate
    const best = unlinked.reduce((a, b) => {
      const diffA = Math.abs(a.date.getTime() - row.dueDate.getTime());
      const diffB = Math.abs(b.date.getTime() - row.dueDate.getTime());
      return diffA <= diffB ? a : b;
    });

    const txAmount = Number(best.amount);
    const status = txAmount >= row.expectedAmount ? 'PAID' : 'PARTIAL';

    await prisma.scheduledTransaction.update({
      where: { id: scheduled.id },
      data: {
        transactionId: best.id,
        actualAmount: txAmount,
        status,
      },
    });
  }

  return result.count;
}

/**
 * Fields on Expense/Income that affect the generated schedule.
 * When any of these change, PENDING ScheduledTransaction rows must be
 * deleted so the lazy generator recreates them with the correct dates.
 */
const SCHEDULE_AFFECTING_FIELDS = [
  'startDate',
  'endDate',
  'frequency',
  'dueDay',
  'dueWeekday',
  'dueOrdinal',
  'skipWeekend',
] as const;

/**
 * Returns true if the update payload contains any field that would change
 * which dates the schedule generator produces for this source.
 */
export function hasScheduleAffectingChange(updateData: Record<string, unknown>): boolean {
  return SCHEDULE_AFFECTING_FIELDS.some((f) => f in updateData);
}

/**
 * Delete ScheduledTransaction rows for a given source so the lazy generator
 * recreates them with the correct dates on the next dashboard load.
 *
 * When `includeSnoozed` is true (schedule-affecting fields changed — dates,
 * frequency, etc.), SNOOZED rows are also deleted because their due dates are
 * no longer valid. PAID and SKIPPED rows are always preserved as historical
 * records.
 *
 * When `includeSnoozed` is false (amount-only changes), only PENDING rows
 * are deleted — the user intentionally snoozed those and only the amount changed.
 */
export async function invalidateSchedule(
  sourceType: 'EXPENSE' | 'INCOME',
  sourceId: string,
  includeSnoozed = false,
): Promise<number> {
  const statuses = includeSnoozed ? (['PENDING', 'SNOOZED'] as const) : (['PENDING'] as const);

  const result = await prisma.scheduledTransaction.deleteMany({
    where: {
      sourceType,
      sourceId,
      status: { in: [...statuses] },
    },
  });
  markScheduleDirty();
  return result.count;
}
